version: 3

tasks:
  test:
    cmds:
      - go test -v ./app/...
  mongo:
    cmds:
      - docker-compose up -d mongodb
  run:
    cmds:
      - go run app/main.go

  docker-build:
    cmds:
      - docker build -t ghcr.io/sonac/snitch/snitch .
